/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.dkafka;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Correlation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7741021667154154805L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Correlation\",\"namespace\":\"io.dkafka\",\"fields\":[{\"name\":\"payer\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Correlation> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Correlation> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Correlation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Correlation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Correlation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Correlation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Correlation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Correlation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Correlation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence payer;
  private java.lang.CharSequence id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Correlation() {}

  /**
   * All-args constructor.
   * @param payer The new value for payer
   * @param id The new value for id
   */
  public Correlation(java.lang.CharSequence payer, java.lang.CharSequence id) {
    this.payer = payer;
    this.id = id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return payer;
    case 1: return id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: payer = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'payer' field.
   * @return The value of the 'payer' field.
   */
  public java.lang.CharSequence getPayer() {
    return payer;
  }


  /**
   * Sets the value of the 'payer' field.
   * @param value the value to set.
   */
  public void setPayer(java.lang.CharSequence value) {
    this.payer = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Creates a new Correlation RecordBuilder.
   * @return A new Correlation RecordBuilder
   */
  public static io.dkafka.Correlation.Builder newBuilder() {
    return new io.dkafka.Correlation.Builder();
  }

  /**
   * Creates a new Correlation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Correlation RecordBuilder
   */
  public static io.dkafka.Correlation.Builder newBuilder(io.dkafka.Correlation.Builder other) {
    if (other == null) {
      return new io.dkafka.Correlation.Builder();
    } else {
      return new io.dkafka.Correlation.Builder(other);
    }
  }

  /**
   * Creates a new Correlation RecordBuilder by copying an existing Correlation instance.
   * @param other The existing instance to copy.
   * @return A new Correlation RecordBuilder
   */
  public static io.dkafka.Correlation.Builder newBuilder(io.dkafka.Correlation other) {
    if (other == null) {
      return new io.dkafka.Correlation.Builder();
    } else {
      return new io.dkafka.Correlation.Builder(other);
    }
  }

  /**
   * RecordBuilder for Correlation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Correlation>
    implements org.apache.avro.data.RecordBuilder<Correlation> {

    private java.lang.CharSequence payer;
    private java.lang.CharSequence id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.dkafka.Correlation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.payer)) {
        this.payer = data().deepCopy(fields()[0].schema(), other.payer);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Correlation instance
     * @param other The existing instance to copy.
     */
    private Builder(io.dkafka.Correlation other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.payer)) {
        this.payer = data().deepCopy(fields()[0].schema(), other.payer);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'payer' field.
      * @return The value.
      */
    public java.lang.CharSequence getPayer() {
      return payer;
    }


    /**
      * Sets the value of the 'payer' field.
      * @param value The value of 'payer'.
      * @return This builder.
      */
    public io.dkafka.Correlation.Builder setPayer(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.payer = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'payer' field has been set.
      * @return True if the 'payer' field has been set, false otherwise.
      */
    public boolean hasPayer() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'payer' field.
      * @return This builder.
      */
    public io.dkafka.Correlation.Builder clearPayer() {
      payer = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.dkafka.Correlation.Builder setId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.dkafka.Correlation.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Correlation build() {
      try {
        Correlation record = new Correlation();
        record.payer = fieldSetFlags()[0] ? this.payer : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Correlation>
    WRITER$ = (org.apache.avro.io.DatumWriter<Correlation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Correlation>
    READER$ = (org.apache.avro.io.DatumReader<Correlation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.payer);

    out.writeString(this.id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.payer = in.readString(this.payer instanceof Utf8 ? (Utf8)this.payer : null);

      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.payer = in.readString(this.payer instanceof Utf8 ? (Utf8)this.payer : null);
          break;

        case 1:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










