/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.dkafka;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DBOpBasic extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3605231581692754348L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DBOpBasic\",\"namespace\":\"io.dkafka\",\"fields\":[{\"name\":\"operation\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"action_index\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"index\",\"type\":\"int\"},{\"name\":\"code\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"scope\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"table_name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"primary_key\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"old_payer\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"new_payer\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"old_data\",\"type\":[\"null\",\"bytes\"],\"default\":null},{\"name\":\"new_data\",\"type\":[\"null\",\"bytes\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DBOpBasic> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DBOpBasic> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DBOpBasic> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DBOpBasic> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DBOpBasic> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DBOpBasic to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DBOpBasic from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DBOpBasic instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DBOpBasic fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Integer operation;
  private java.lang.Long action_index;
  private int index;
  private java.lang.CharSequence code;
  private java.lang.CharSequence scope;
  private java.lang.CharSequence table_name;
  private java.lang.CharSequence primary_key;
  private java.lang.CharSequence old_payer;
  private java.lang.CharSequence new_payer;
  private java.nio.ByteBuffer old_data;
  private java.nio.ByteBuffer new_data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DBOpBasic() {}

  /**
   * All-args constructor.
   * @param operation The new value for operation
   * @param action_index The new value for action_index
   * @param index The new value for index
   * @param code The new value for code
   * @param scope The new value for scope
   * @param table_name The new value for table_name
   * @param primary_key The new value for primary_key
   * @param old_payer The new value for old_payer
   * @param new_payer The new value for new_payer
   * @param old_data The new value for old_data
   * @param new_data The new value for new_data
   */
  public DBOpBasic(java.lang.Integer operation, java.lang.Long action_index, java.lang.Integer index, java.lang.CharSequence code, java.lang.CharSequence scope, java.lang.CharSequence table_name, java.lang.CharSequence primary_key, java.lang.CharSequence old_payer, java.lang.CharSequence new_payer, java.nio.ByteBuffer old_data, java.nio.ByteBuffer new_data) {
    this.operation = operation;
    this.action_index = action_index;
    this.index = index;
    this.code = code;
    this.scope = scope;
    this.table_name = table_name;
    this.primary_key = primary_key;
    this.old_payer = old_payer;
    this.new_payer = new_payer;
    this.old_data = old_data;
    this.new_data = new_data;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return operation;
    case 1: return action_index;
    case 2: return index;
    case 3: return code;
    case 4: return scope;
    case 5: return table_name;
    case 6: return primary_key;
    case 7: return old_payer;
    case 8: return new_payer;
    case 9: return old_data;
    case 10: return new_data;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: operation = (java.lang.Integer)value$; break;
    case 1: action_index = (java.lang.Long)value$; break;
    case 2: index = (java.lang.Integer)value$; break;
    case 3: code = (java.lang.CharSequence)value$; break;
    case 4: scope = (java.lang.CharSequence)value$; break;
    case 5: table_name = (java.lang.CharSequence)value$; break;
    case 6: primary_key = (java.lang.CharSequence)value$; break;
    case 7: old_payer = (java.lang.CharSequence)value$; break;
    case 8: new_payer = (java.lang.CharSequence)value$; break;
    case 9: old_data = (java.nio.ByteBuffer)value$; break;
    case 10: new_data = (java.nio.ByteBuffer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'operation' field.
   * @return The value of the 'operation' field.
   */
  public java.lang.Integer getOperation() {
    return operation;
  }


  /**
   * Sets the value of the 'operation' field.
   * @param value the value to set.
   */
  public void setOperation(java.lang.Integer value) {
    this.operation = value;
  }

  /**
   * Gets the value of the 'action_index' field.
   * @return The value of the 'action_index' field.
   */
  public java.lang.Long getActionIndex() {
    return action_index;
  }


  /**
   * Sets the value of the 'action_index' field.
   * @param value the value to set.
   */
  public void setActionIndex(java.lang.Long value) {
    this.action_index = value;
  }

  /**
   * Gets the value of the 'index' field.
   * @return The value of the 'index' field.
   */
  public int getIndex() {
    return index;
  }


  /**
   * Sets the value of the 'index' field.
   * @param value the value to set.
   */
  public void setIndex(int value) {
    this.index = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'scope' field.
   * @return The value of the 'scope' field.
   */
  public java.lang.CharSequence getScope() {
    return scope;
  }


  /**
   * Sets the value of the 'scope' field.
   * @param value the value to set.
   */
  public void setScope(java.lang.CharSequence value) {
    this.scope = value;
  }

  /**
   * Gets the value of the 'table_name' field.
   * @return The value of the 'table_name' field.
   */
  public java.lang.CharSequence getTableName() {
    return table_name;
  }


  /**
   * Sets the value of the 'table_name' field.
   * @param value the value to set.
   */
  public void setTableName(java.lang.CharSequence value) {
    this.table_name = value;
  }

  /**
   * Gets the value of the 'primary_key' field.
   * @return The value of the 'primary_key' field.
   */
  public java.lang.CharSequence getPrimaryKey() {
    return primary_key;
  }


  /**
   * Sets the value of the 'primary_key' field.
   * @param value the value to set.
   */
  public void setPrimaryKey(java.lang.CharSequence value) {
    this.primary_key = value;
  }

  /**
   * Gets the value of the 'old_payer' field.
   * @return The value of the 'old_payer' field.
   */
  public java.lang.CharSequence getOldPayer() {
    return old_payer;
  }


  /**
   * Sets the value of the 'old_payer' field.
   * @param value the value to set.
   */
  public void setOldPayer(java.lang.CharSequence value) {
    this.old_payer = value;
  }

  /**
   * Gets the value of the 'new_payer' field.
   * @return The value of the 'new_payer' field.
   */
  public java.lang.CharSequence getNewPayer() {
    return new_payer;
  }


  /**
   * Sets the value of the 'new_payer' field.
   * @param value the value to set.
   */
  public void setNewPayer(java.lang.CharSequence value) {
    this.new_payer = value;
  }

  /**
   * Gets the value of the 'old_data' field.
   * @return The value of the 'old_data' field.
   */
  public java.nio.ByteBuffer getOldData() {
    return old_data;
  }


  /**
   * Sets the value of the 'old_data' field.
   * @param value the value to set.
   */
  public void setOldData(java.nio.ByteBuffer value) {
    this.old_data = value;
  }

  /**
   * Gets the value of the 'new_data' field.
   * @return The value of the 'new_data' field.
   */
  public java.nio.ByteBuffer getNewData() {
    return new_data;
  }


  /**
   * Sets the value of the 'new_data' field.
   * @param value the value to set.
   */
  public void setNewData(java.nio.ByteBuffer value) {
    this.new_data = value;
  }

  /**
   * Creates a new DBOpBasic RecordBuilder.
   * @return A new DBOpBasic RecordBuilder
   */
  public static io.dkafka.DBOpBasic.Builder newBuilder() {
    return new io.dkafka.DBOpBasic.Builder();
  }

  /**
   * Creates a new DBOpBasic RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DBOpBasic RecordBuilder
   */
  public static io.dkafka.DBOpBasic.Builder newBuilder(io.dkafka.DBOpBasic.Builder other) {
    if (other == null) {
      return new io.dkafka.DBOpBasic.Builder();
    } else {
      return new io.dkafka.DBOpBasic.Builder(other);
    }
  }

  /**
   * Creates a new DBOpBasic RecordBuilder by copying an existing DBOpBasic instance.
   * @param other The existing instance to copy.
   * @return A new DBOpBasic RecordBuilder
   */
  public static io.dkafka.DBOpBasic.Builder newBuilder(io.dkafka.DBOpBasic other) {
    if (other == null) {
      return new io.dkafka.DBOpBasic.Builder();
    } else {
      return new io.dkafka.DBOpBasic.Builder(other);
    }
  }

  /**
   * RecordBuilder for DBOpBasic instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DBOpBasic>
    implements org.apache.avro.data.RecordBuilder<DBOpBasic> {

    private java.lang.Integer operation;
    private java.lang.Long action_index;
    private int index;
    private java.lang.CharSequence code;
    private java.lang.CharSequence scope;
    private java.lang.CharSequence table_name;
    private java.lang.CharSequence primary_key;
    private java.lang.CharSequence old_payer;
    private java.lang.CharSequence new_payer;
    private java.nio.ByteBuffer old_data;
    private java.nio.ByteBuffer new_data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.dkafka.DBOpBasic.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.operation)) {
        this.operation = data().deepCopy(fields()[0].schema(), other.operation);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.action_index)) {
        this.action_index = data().deepCopy(fields()[1].schema(), other.action_index);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.index)) {
        this.index = data().deepCopy(fields()[2].schema(), other.index);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.code)) {
        this.code = data().deepCopy(fields()[3].schema(), other.code);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.scope)) {
        this.scope = data().deepCopy(fields()[4].schema(), other.scope);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.table_name)) {
        this.table_name = data().deepCopy(fields()[5].schema(), other.table_name);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.primary_key)) {
        this.primary_key = data().deepCopy(fields()[6].schema(), other.primary_key);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.old_payer)) {
        this.old_payer = data().deepCopy(fields()[7].schema(), other.old_payer);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.new_payer)) {
        this.new_payer = data().deepCopy(fields()[8].schema(), other.new_payer);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.old_data)) {
        this.old_data = data().deepCopy(fields()[9].schema(), other.old_data);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.new_data)) {
        this.new_data = data().deepCopy(fields()[10].schema(), other.new_data);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing DBOpBasic instance
     * @param other The existing instance to copy.
     */
    private Builder(io.dkafka.DBOpBasic other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.operation)) {
        this.operation = data().deepCopy(fields()[0].schema(), other.operation);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.action_index)) {
        this.action_index = data().deepCopy(fields()[1].schema(), other.action_index);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.index)) {
        this.index = data().deepCopy(fields()[2].schema(), other.index);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.code)) {
        this.code = data().deepCopy(fields()[3].schema(), other.code);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.scope)) {
        this.scope = data().deepCopy(fields()[4].schema(), other.scope);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.table_name)) {
        this.table_name = data().deepCopy(fields()[5].schema(), other.table_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.primary_key)) {
        this.primary_key = data().deepCopy(fields()[6].schema(), other.primary_key);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.old_payer)) {
        this.old_payer = data().deepCopy(fields()[7].schema(), other.old_payer);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.new_payer)) {
        this.new_payer = data().deepCopy(fields()[8].schema(), other.new_payer);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.old_data)) {
        this.old_data = data().deepCopy(fields()[9].schema(), other.old_data);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.new_data)) {
        this.new_data = data().deepCopy(fields()[10].schema(), other.new_data);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'operation' field.
      * @return The value.
      */
    public java.lang.Integer getOperation() {
      return operation;
    }


    /**
      * Sets the value of the 'operation' field.
      * @param value The value of 'operation'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setOperation(java.lang.Integer value) {
      validate(fields()[0], value);
      this.operation = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'operation' field has been set.
      * @return True if the 'operation' field has been set, false otherwise.
      */
    public boolean hasOperation() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'operation' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearOperation() {
      operation = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'action_index' field.
      * @return The value.
      */
    public java.lang.Long getActionIndex() {
      return action_index;
    }


    /**
      * Sets the value of the 'action_index' field.
      * @param value The value of 'action_index'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setActionIndex(java.lang.Long value) {
      validate(fields()[1], value);
      this.action_index = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'action_index' field has been set.
      * @return True if the 'action_index' field has been set, false otherwise.
      */
    public boolean hasActionIndex() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'action_index' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearActionIndex() {
      action_index = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'index' field.
      * @return The value.
      */
    public int getIndex() {
      return index;
    }


    /**
      * Sets the value of the 'index' field.
      * @param value The value of 'index'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setIndex(int value) {
      validate(fields()[2], value);
      this.index = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'index' field has been set.
      * @return True if the 'index' field has been set, false otherwise.
      */
    public boolean hasIndex() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'index' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearIndex() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.code = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearCode() {
      code = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'scope' field.
      * @return The value.
      */
    public java.lang.CharSequence getScope() {
      return scope;
    }


    /**
      * Sets the value of the 'scope' field.
      * @param value The value of 'scope'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setScope(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.scope = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'scope' field has been set.
      * @return True if the 'scope' field has been set, false otherwise.
      */
    public boolean hasScope() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'scope' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearScope() {
      scope = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'table_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getTableName() {
      return table_name;
    }


    /**
      * Sets the value of the 'table_name' field.
      * @param value The value of 'table_name'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setTableName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.table_name = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'table_name' field has been set.
      * @return True if the 'table_name' field has been set, false otherwise.
      */
    public boolean hasTableName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'table_name' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearTableName() {
      table_name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'primary_key' field.
      * @return The value.
      */
    public java.lang.CharSequence getPrimaryKey() {
      return primary_key;
    }


    /**
      * Sets the value of the 'primary_key' field.
      * @param value The value of 'primary_key'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setPrimaryKey(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.primary_key = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'primary_key' field has been set.
      * @return True if the 'primary_key' field has been set, false otherwise.
      */
    public boolean hasPrimaryKey() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'primary_key' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearPrimaryKey() {
      primary_key = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_payer' field.
      * @return The value.
      */
    public java.lang.CharSequence getOldPayer() {
      return old_payer;
    }


    /**
      * Sets the value of the 'old_payer' field.
      * @param value The value of 'old_payer'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setOldPayer(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.old_payer = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'old_payer' field has been set.
      * @return True if the 'old_payer' field has been set, false otherwise.
      */
    public boolean hasOldPayer() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'old_payer' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearOldPayer() {
      old_payer = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_payer' field.
      * @return The value.
      */
    public java.lang.CharSequence getNewPayer() {
      return new_payer;
    }


    /**
      * Sets the value of the 'new_payer' field.
      * @param value The value of 'new_payer'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setNewPayer(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.new_payer = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'new_payer' field has been set.
      * @return True if the 'new_payer' field has been set, false otherwise.
      */
    public boolean hasNewPayer() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'new_payer' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearNewPayer() {
      new_payer = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_data' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getOldData() {
      return old_data;
    }


    /**
      * Sets the value of the 'old_data' field.
      * @param value The value of 'old_data'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setOldData(java.nio.ByteBuffer value) {
      validate(fields()[9], value);
      this.old_data = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'old_data' field has been set.
      * @return True if the 'old_data' field has been set, false otherwise.
      */
    public boolean hasOldData() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'old_data' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearOldData() {
      old_data = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_data' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getNewData() {
      return new_data;
    }


    /**
      * Sets the value of the 'new_data' field.
      * @param value The value of 'new_data'.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder setNewData(java.nio.ByteBuffer value) {
      validate(fields()[10], value);
      this.new_data = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'new_data' field has been set.
      * @return True if the 'new_data' field has been set, false otherwise.
      */
    public boolean hasNewData() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'new_data' field.
      * @return This builder.
      */
    public io.dkafka.DBOpBasic.Builder clearNewData() {
      new_data = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DBOpBasic build() {
      try {
        DBOpBasic record = new DBOpBasic();
        record.operation = fieldSetFlags()[0] ? this.operation : (java.lang.Integer) defaultValue(fields()[0]);
        record.action_index = fieldSetFlags()[1] ? this.action_index : (java.lang.Long) defaultValue(fields()[1]);
        record.index = fieldSetFlags()[2] ? this.index : (java.lang.Integer) defaultValue(fields()[2]);
        record.code = fieldSetFlags()[3] ? this.code : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.scope = fieldSetFlags()[4] ? this.scope : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.table_name = fieldSetFlags()[5] ? this.table_name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.primary_key = fieldSetFlags()[6] ? this.primary_key : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.old_payer = fieldSetFlags()[7] ? this.old_payer : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.new_payer = fieldSetFlags()[8] ? this.new_payer : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.old_data = fieldSetFlags()[9] ? this.old_data : (java.nio.ByteBuffer) defaultValue(fields()[9]);
        record.new_data = fieldSetFlags()[10] ? this.new_data : (java.nio.ByteBuffer) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DBOpBasic>
    WRITER$ = (org.apache.avro.io.DatumWriter<DBOpBasic>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DBOpBasic>
    READER$ = (org.apache.avro.io.DatumReader<DBOpBasic>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.operation == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.operation);
    }

    if (this.action_index == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.action_index);
    }

    out.writeInt(this.index);

    if (this.code == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.code);
    }

    if (this.scope == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.scope);
    }

    if (this.table_name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.table_name);
    }

    if (this.primary_key == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.primary_key);
    }

    if (this.old_payer == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.old_payer);
    }

    if (this.new_payer == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.new_payer);
    }

    if (this.old_data == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBytes(this.old_data);
    }

    if (this.new_data == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBytes(this.new_data);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.operation = null;
      } else {
        this.operation = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.action_index = null;
      } else {
        this.action_index = in.readLong();
      }

      this.index = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.code = null;
      } else {
        this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.scope = null;
      } else {
        this.scope = in.readString(this.scope instanceof Utf8 ? (Utf8)this.scope : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.table_name = null;
      } else {
        this.table_name = in.readString(this.table_name instanceof Utf8 ? (Utf8)this.table_name : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.primary_key = null;
      } else {
        this.primary_key = in.readString(this.primary_key instanceof Utf8 ? (Utf8)this.primary_key : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.old_payer = null;
      } else {
        this.old_payer = in.readString(this.old_payer instanceof Utf8 ? (Utf8)this.old_payer : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.new_payer = null;
      } else {
        this.new_payer = in.readString(this.new_payer instanceof Utf8 ? (Utf8)this.new_payer : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.old_data = null;
      } else {
        this.old_data = in.readBytes(this.old_data);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.new_data = null;
      } else {
        this.new_data = in.readBytes(this.new_data);
      }

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.operation = null;
          } else {
            this.operation = in.readInt();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.action_index = null;
          } else {
            this.action_index = in.readLong();
          }
          break;

        case 2:
          this.index = in.readInt();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.code = null;
          } else {
            this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.scope = null;
          } else {
            this.scope = in.readString(this.scope instanceof Utf8 ? (Utf8)this.scope : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.table_name = null;
          } else {
            this.table_name = in.readString(this.table_name instanceof Utf8 ? (Utf8)this.table_name : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.primary_key = null;
          } else {
            this.primary_key = in.readString(this.primary_key instanceof Utf8 ? (Utf8)this.primary_key : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.old_payer = null;
          } else {
            this.old_payer = in.readString(this.old_payer instanceof Utf8 ? (Utf8)this.old_payer : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.new_payer = null;
          } else {
            this.new_payer = in.readString(this.new_payer instanceof Utf8 ? (Utf8)this.new_payer : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.old_data = null;
          } else {
            this.old_data = in.readBytes(this.old_data);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.new_data = null;
          } else {
            this.new_data = in.readBytes(this.new_data);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










