/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.dkafka;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NotificationContext extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8529448449130969427L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NotificationContext\",\"namespace\":\"io.dkafka\",\"fields\":[{\"name\":\"block_num\",\"type\":\"long\"},{\"name\":\"block_id\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"executed\",\"type\":\"boolean\"},{\"name\":\"block_step\",\"type\":\"string\"},{\"name\":\"correlation\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Correlation\",\"fields\":[{\"name\":\"payer\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"string\"}]}],\"default\":null},{\"name\":\"trx_id\",\"type\":\"string\"},{\"name\":\"time\",\"type\":{\"type\":\"long\",\"eos.type\":\"block_timestamp_type\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"cursor\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<NotificationContext> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NotificationContext> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NotificationContext> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NotificationContext> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NotificationContext> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NotificationContext to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NotificationContext from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NotificationContext instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NotificationContext fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long block_num;
  private java.lang.CharSequence block_id;
  private java.lang.CharSequence status;
  private boolean executed;
  private java.lang.CharSequence block_step;
  private io.dkafka.Correlation correlation;
  private java.lang.CharSequence trx_id;
  private java.time.Instant time;
  private java.lang.CharSequence cursor;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NotificationContext() {}

  /**
   * All-args constructor.
   * @param block_num The new value for block_num
   * @param block_id The new value for block_id
   * @param status The new value for status
   * @param executed The new value for executed
   * @param block_step The new value for block_step
   * @param correlation The new value for correlation
   * @param trx_id The new value for trx_id
   * @param time The new value for time
   * @param cursor The new value for cursor
   */
  public NotificationContext(java.lang.Long block_num, java.lang.CharSequence block_id, java.lang.CharSequence status, java.lang.Boolean executed, java.lang.CharSequence block_step, io.dkafka.Correlation correlation, java.lang.CharSequence trx_id, java.time.Instant time, java.lang.CharSequence cursor) {
    this.block_num = block_num;
    this.block_id = block_id;
    this.status = status;
    this.executed = executed;
    this.block_step = block_step;
    this.correlation = correlation;
    this.trx_id = trx_id;
    this.time = time.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.cursor = cursor;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return block_num;
    case 1: return block_id;
    case 2: return status;
    case 3: return executed;
    case 4: return block_step;
    case 5: return correlation;
    case 6: return trx_id;
    case 7: return time;
    case 8: return cursor;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: block_num = (java.lang.Long)value$; break;
    case 1: block_id = (java.lang.CharSequence)value$; break;
    case 2: status = (java.lang.CharSequence)value$; break;
    case 3: executed = (java.lang.Boolean)value$; break;
    case 4: block_step = (java.lang.CharSequence)value$; break;
    case 5: correlation = (io.dkafka.Correlation)value$; break;
    case 6: trx_id = (java.lang.CharSequence)value$; break;
    case 7: time = (java.time.Instant)value$; break;
    case 8: cursor = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'block_num' field.
   * @return The value of the 'block_num' field.
   */
  public long getBlockNum() {
    return block_num;
  }


  /**
   * Sets the value of the 'block_num' field.
   * @param value the value to set.
   */
  public void setBlockNum(long value) {
    this.block_num = value;
  }

  /**
   * Gets the value of the 'block_id' field.
   * @return The value of the 'block_id' field.
   */
  public java.lang.CharSequence getBlockId() {
    return block_id;
  }


  /**
   * Sets the value of the 'block_id' field.
   * @param value the value to set.
   */
  public void setBlockId(java.lang.CharSequence value) {
    this.block_id = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'executed' field.
   * @return The value of the 'executed' field.
   */
  public boolean getExecuted() {
    return executed;
  }


  /**
   * Sets the value of the 'executed' field.
   * @param value the value to set.
   */
  public void setExecuted(boolean value) {
    this.executed = value;
  }

  /**
   * Gets the value of the 'block_step' field.
   * @return The value of the 'block_step' field.
   */
  public java.lang.CharSequence getBlockStep() {
    return block_step;
  }


  /**
   * Sets the value of the 'block_step' field.
   * @param value the value to set.
   */
  public void setBlockStep(java.lang.CharSequence value) {
    this.block_step = value;
  }

  /**
   * Gets the value of the 'correlation' field.
   * @return The value of the 'correlation' field.
   */
  public io.dkafka.Correlation getCorrelation() {
    return correlation;
  }


  /**
   * Sets the value of the 'correlation' field.
   * @param value the value to set.
   */
  public void setCorrelation(io.dkafka.Correlation value) {
    this.correlation = value;
  }

  /**
   * Gets the value of the 'trx_id' field.
   * @return The value of the 'trx_id' field.
   */
  public java.lang.CharSequence getTrxId() {
    return trx_id;
  }


  /**
   * Sets the value of the 'trx_id' field.
   * @param value the value to set.
   */
  public void setTrxId(java.lang.CharSequence value) {
    this.trx_id = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public java.time.Instant getTime() {
    return time;
  }


  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.time.Instant value) {
    this.time = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'cursor' field.
   * @return The value of the 'cursor' field.
   */
  public java.lang.CharSequence getCursor() {
    return cursor;
  }


  /**
   * Sets the value of the 'cursor' field.
   * @param value the value to set.
   */
  public void setCursor(java.lang.CharSequence value) {
    this.cursor = value;
  }

  /**
   * Creates a new NotificationContext RecordBuilder.
   * @return A new NotificationContext RecordBuilder
   */
  public static io.dkafka.NotificationContext.Builder newBuilder() {
    return new io.dkafka.NotificationContext.Builder();
  }

  /**
   * Creates a new NotificationContext RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NotificationContext RecordBuilder
   */
  public static io.dkafka.NotificationContext.Builder newBuilder(io.dkafka.NotificationContext.Builder other) {
    if (other == null) {
      return new io.dkafka.NotificationContext.Builder();
    } else {
      return new io.dkafka.NotificationContext.Builder(other);
    }
  }

  /**
   * Creates a new NotificationContext RecordBuilder by copying an existing NotificationContext instance.
   * @param other The existing instance to copy.
   * @return A new NotificationContext RecordBuilder
   */
  public static io.dkafka.NotificationContext.Builder newBuilder(io.dkafka.NotificationContext other) {
    if (other == null) {
      return new io.dkafka.NotificationContext.Builder();
    } else {
      return new io.dkafka.NotificationContext.Builder(other);
    }
  }

  /**
   * RecordBuilder for NotificationContext instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NotificationContext>
    implements org.apache.avro.data.RecordBuilder<NotificationContext> {

    private long block_num;
    private java.lang.CharSequence block_id;
    private java.lang.CharSequence status;
    private boolean executed;
    private java.lang.CharSequence block_step;
    private io.dkafka.Correlation correlation;
    private io.dkafka.Correlation.Builder correlationBuilder;
    private java.lang.CharSequence trx_id;
    private java.time.Instant time;
    private java.lang.CharSequence cursor;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.dkafka.NotificationContext.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.block_num)) {
        this.block_num = data().deepCopy(fields()[0].schema(), other.block_num);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.block_id)) {
        this.block_id = data().deepCopy(fields()[1].schema(), other.block_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.executed)) {
        this.executed = data().deepCopy(fields()[3].schema(), other.executed);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.block_step)) {
        this.block_step = data().deepCopy(fields()[4].schema(), other.block_step);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.correlation)) {
        this.correlation = data().deepCopy(fields()[5].schema(), other.correlation);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (other.hasCorrelationBuilder()) {
        this.correlationBuilder = io.dkafka.Correlation.newBuilder(other.getCorrelationBuilder());
      }
      if (isValidValue(fields()[6], other.trx_id)) {
        this.trx_id = data().deepCopy(fields()[6].schema(), other.trx_id);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.time)) {
        this.time = data().deepCopy(fields()[7].schema(), other.time);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.cursor)) {
        this.cursor = data().deepCopy(fields()[8].schema(), other.cursor);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing NotificationContext instance
     * @param other The existing instance to copy.
     */
    private Builder(io.dkafka.NotificationContext other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.block_num)) {
        this.block_num = data().deepCopy(fields()[0].schema(), other.block_num);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.block_id)) {
        this.block_id = data().deepCopy(fields()[1].schema(), other.block_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.executed)) {
        this.executed = data().deepCopy(fields()[3].schema(), other.executed);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.block_step)) {
        this.block_step = data().deepCopy(fields()[4].schema(), other.block_step);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.correlation)) {
        this.correlation = data().deepCopy(fields()[5].schema(), other.correlation);
        fieldSetFlags()[5] = true;
      }
      this.correlationBuilder = null;
      if (isValidValue(fields()[6], other.trx_id)) {
        this.trx_id = data().deepCopy(fields()[6].schema(), other.trx_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.time)) {
        this.time = data().deepCopy(fields()[7].schema(), other.time);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.cursor)) {
        this.cursor = data().deepCopy(fields()[8].schema(), other.cursor);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'block_num' field.
      * @return The value.
      */
    public long getBlockNum() {
      return block_num;
    }


    /**
      * Sets the value of the 'block_num' field.
      * @param value The value of 'block_num'.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder setBlockNum(long value) {
      validate(fields()[0], value);
      this.block_num = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'block_num' field has been set.
      * @return True if the 'block_num' field has been set, false otherwise.
      */
    public boolean hasBlockNum() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'block_num' field.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder clearBlockNum() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'block_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getBlockId() {
      return block_id;
    }


    /**
      * Sets the value of the 'block_id' field.
      * @param value The value of 'block_id'.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder setBlockId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.block_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'block_id' field has been set.
      * @return True if the 'block_id' field has been set, false otherwise.
      */
    public boolean hasBlockId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'block_id' field.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder clearBlockId() {
      block_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'executed' field.
      * @return The value.
      */
    public boolean getExecuted() {
      return executed;
    }


    /**
      * Sets the value of the 'executed' field.
      * @param value The value of 'executed'.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder setExecuted(boolean value) {
      validate(fields()[3], value);
      this.executed = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'executed' field has been set.
      * @return True if the 'executed' field has been set, false otherwise.
      */
    public boolean hasExecuted() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'executed' field.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder clearExecuted() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'block_step' field.
      * @return The value.
      */
    public java.lang.CharSequence getBlockStep() {
      return block_step;
    }


    /**
      * Sets the value of the 'block_step' field.
      * @param value The value of 'block_step'.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder setBlockStep(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.block_step = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'block_step' field has been set.
      * @return True if the 'block_step' field has been set, false otherwise.
      */
    public boolean hasBlockStep() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'block_step' field.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder clearBlockStep() {
      block_step = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'correlation' field.
      * @return The value.
      */
    public io.dkafka.Correlation getCorrelation() {
      return correlation;
    }


    /**
      * Sets the value of the 'correlation' field.
      * @param value The value of 'correlation'.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder setCorrelation(io.dkafka.Correlation value) {
      validate(fields()[5], value);
      this.correlationBuilder = null;
      this.correlation = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'correlation' field has been set.
      * @return True if the 'correlation' field has been set, false otherwise.
      */
    public boolean hasCorrelation() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'correlation' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.dkafka.Correlation.Builder getCorrelationBuilder() {
      if (correlationBuilder == null) {
        if (hasCorrelation()) {
          setCorrelationBuilder(io.dkafka.Correlation.newBuilder(correlation));
        } else {
          setCorrelationBuilder(io.dkafka.Correlation.newBuilder());
        }
      }
      return correlationBuilder;
    }

    /**
     * Sets the Builder instance for the 'correlation' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public io.dkafka.NotificationContext.Builder setCorrelationBuilder(io.dkafka.Correlation.Builder value) {
      clearCorrelation();
      correlationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'correlation' field has an active Builder instance
     * @return True if the 'correlation' field has an active Builder instance
     */
    public boolean hasCorrelationBuilder() {
      return correlationBuilder != null;
    }

    /**
      * Clears the value of the 'correlation' field.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder clearCorrelation() {
      correlation = null;
      correlationBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'trx_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getTrxId() {
      return trx_id;
    }


    /**
      * Sets the value of the 'trx_id' field.
      * @param value The value of 'trx_id'.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder setTrxId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.trx_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'trx_id' field has been set.
      * @return True if the 'trx_id' field has been set, false otherwise.
      */
    public boolean hasTrxId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'trx_id' field.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder clearTrxId() {
      trx_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public java.time.Instant getTime() {
      return time;
    }


    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder setTime(java.time.Instant value) {
      validate(fields()[7], value);
      this.time = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder clearTime() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'cursor' field.
      * @return The value.
      */
    public java.lang.CharSequence getCursor() {
      return cursor;
    }


    /**
      * Sets the value of the 'cursor' field.
      * @param value The value of 'cursor'.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder setCursor(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.cursor = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'cursor' field has been set.
      * @return True if the 'cursor' field has been set, false otherwise.
      */
    public boolean hasCursor() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'cursor' field.
      * @return This builder.
      */
    public io.dkafka.NotificationContext.Builder clearCursor() {
      cursor = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NotificationContext build() {
      try {
        NotificationContext record = new NotificationContext();
        record.block_num = fieldSetFlags()[0] ? this.block_num : (java.lang.Long) defaultValue(fields()[0]);
        record.block_id = fieldSetFlags()[1] ? this.block_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.executed = fieldSetFlags()[3] ? this.executed : (java.lang.Boolean) defaultValue(fields()[3]);
        record.block_step = fieldSetFlags()[4] ? this.block_step : (java.lang.CharSequence) defaultValue(fields()[4]);
        if (correlationBuilder != null) {
          try {
            record.correlation = this.correlationBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("correlation"));
            throw e;
          }
        } else {
          record.correlation = fieldSetFlags()[5] ? this.correlation : (io.dkafka.Correlation) defaultValue(fields()[5]);
        }
        record.trx_id = fieldSetFlags()[6] ? this.trx_id : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.time = fieldSetFlags()[7] ? this.time : (java.time.Instant) defaultValue(fields()[7]);
        record.cursor = fieldSetFlags()[8] ? this.cursor : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NotificationContext>
    WRITER$ = (org.apache.avro.io.DatumWriter<NotificationContext>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NotificationContext>
    READER$ = (org.apache.avro.io.DatumReader<NotificationContext>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










