/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eosio.nft.ft;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AddkeysAActionParams extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8384104660850887308L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AddkeysAActionParams\",\"namespace\":\"eosio.nft.ft\",\"fields\":[{\"name\":\"factory_id\",\"type\":{\"type\":\"long\",\"eos.type\":\"uint64\",\"logicalType\":\"eos.uint64\"}},{\"name\":\"key_defs\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"KeyDefAction\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"eos.type\":\"string\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"eos.type\":\"string\"}},{\"name\":\"edit_rights\",\"type\":{\"type\":\"int\",\"eos.type\":\"uint8\"}},{\"name\":\"editors\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"eos.type\":\"name\"}}},{\"name\":\"default_value\",\"type\":[\"null\",{\"type\":\"int\",\"eos.type\":[\"int8\",\"int16\"]},{\"type\":\"long\",\"eos.type\":\"int64\"},{\"type\":\"float\",\"eos.type\":\"float32\"},{\"type\":\"double\",\"eos.type\":\"float64\"},{\"type\":\"string\",\"eos.type\":\"string\"},{\"type\":\"bytes\",\"eos.type\":\"bytes\"},{\"type\":\"array\",\"items\":[{\"type\":\"int\",\"eos.type\":[\"int16\",\"int32\"]}]}],\"default\":null}]}}},{\"name\":\"memo\",\"type\":{\"type\":\"string\",\"eos.type\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AddkeysAActionParams> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AddkeysAActionParams> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AddkeysAActionParams> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AddkeysAActionParams> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AddkeysAActionParams> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AddkeysAActionParams to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AddkeysAActionParams from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AddkeysAActionParams instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AddkeysAActionParams fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long factory_id;
  private java.util.List<eosio.nft.ft.KeyDefAction> key_defs;
  private java.lang.CharSequence memo;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AddkeysAActionParams() {}

  /**
   * All-args constructor.
   * @param factory_id The new value for factory_id
   * @param key_defs The new value for key_defs
   * @param memo The new value for memo
   */
  public AddkeysAActionParams(java.lang.Long factory_id, java.util.List<eosio.nft.ft.KeyDefAction> key_defs, java.lang.CharSequence memo) {
    this.factory_id = factory_id;
    this.key_defs = key_defs;
    this.memo = memo;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return factory_id;
    case 1: return key_defs;
    case 2: return memo;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: factory_id = (java.lang.Long)value$; break;
    case 1: key_defs = (java.util.List<eosio.nft.ft.KeyDefAction>)value$; break;
    case 2: memo = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'factory_id' field.
   * @return The value of the 'factory_id' field.
   */
  public long getFactoryId() {
    return factory_id;
  }


  /**
   * Sets the value of the 'factory_id' field.
   * @param value the value to set.
   */
  public void setFactoryId(long value) {
    this.factory_id = value;
  }

  /**
   * Gets the value of the 'key_defs' field.
   * @return The value of the 'key_defs' field.
   */
  public java.util.List<eosio.nft.ft.KeyDefAction> getKeyDefs() {
    return key_defs;
  }


  /**
   * Sets the value of the 'key_defs' field.
   * @param value the value to set.
   */
  public void setKeyDefs(java.util.List<eosio.nft.ft.KeyDefAction> value) {
    this.key_defs = value;
  }

  /**
   * Gets the value of the 'memo' field.
   * @return The value of the 'memo' field.
   */
  public java.lang.CharSequence getMemo() {
    return memo;
  }


  /**
   * Sets the value of the 'memo' field.
   * @param value the value to set.
   */
  public void setMemo(java.lang.CharSequence value) {
    this.memo = value;
  }

  /**
   * Creates a new AddkeysAActionParams RecordBuilder.
   * @return A new AddkeysAActionParams RecordBuilder
   */
  public static eosio.nft.ft.AddkeysAActionParams.Builder newBuilder() {
    return new eosio.nft.ft.AddkeysAActionParams.Builder();
  }

  /**
   * Creates a new AddkeysAActionParams RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AddkeysAActionParams RecordBuilder
   */
  public static eosio.nft.ft.AddkeysAActionParams.Builder newBuilder(eosio.nft.ft.AddkeysAActionParams.Builder other) {
    if (other == null) {
      return new eosio.nft.ft.AddkeysAActionParams.Builder();
    } else {
      return new eosio.nft.ft.AddkeysAActionParams.Builder(other);
    }
  }

  /**
   * Creates a new AddkeysAActionParams RecordBuilder by copying an existing AddkeysAActionParams instance.
   * @param other The existing instance to copy.
   * @return A new AddkeysAActionParams RecordBuilder
   */
  public static eosio.nft.ft.AddkeysAActionParams.Builder newBuilder(eosio.nft.ft.AddkeysAActionParams other) {
    if (other == null) {
      return new eosio.nft.ft.AddkeysAActionParams.Builder();
    } else {
      return new eosio.nft.ft.AddkeysAActionParams.Builder(other);
    }
  }

  /**
   * RecordBuilder for AddkeysAActionParams instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AddkeysAActionParams>
    implements org.apache.avro.data.RecordBuilder<AddkeysAActionParams> {

    private long factory_id;
    private java.util.List<eosio.nft.ft.KeyDefAction> key_defs;
    private java.lang.CharSequence memo;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eosio.nft.ft.AddkeysAActionParams.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.factory_id)) {
        this.factory_id = data().deepCopy(fields()[0].schema(), other.factory_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.key_defs)) {
        this.key_defs = data().deepCopy(fields()[1].schema(), other.key_defs);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.memo)) {
        this.memo = data().deepCopy(fields()[2].schema(), other.memo);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AddkeysAActionParams instance
     * @param other The existing instance to copy.
     */
    private Builder(eosio.nft.ft.AddkeysAActionParams other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.factory_id)) {
        this.factory_id = data().deepCopy(fields()[0].schema(), other.factory_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.key_defs)) {
        this.key_defs = data().deepCopy(fields()[1].schema(), other.key_defs);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.memo)) {
        this.memo = data().deepCopy(fields()[2].schema(), other.memo);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'factory_id' field.
      * @return The value.
      */
    public long getFactoryId() {
      return factory_id;
    }


    /**
      * Sets the value of the 'factory_id' field.
      * @param value The value of 'factory_id'.
      * @return This builder.
      */
    public eosio.nft.ft.AddkeysAActionParams.Builder setFactoryId(long value) {
      validate(fields()[0], value);
      this.factory_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'factory_id' field has been set.
      * @return True if the 'factory_id' field has been set, false otherwise.
      */
    public boolean hasFactoryId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'factory_id' field.
      * @return This builder.
      */
    public eosio.nft.ft.AddkeysAActionParams.Builder clearFactoryId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'key_defs' field.
      * @return The value.
      */
    public java.util.List<eosio.nft.ft.KeyDefAction> getKeyDefs() {
      return key_defs;
    }


    /**
      * Sets the value of the 'key_defs' field.
      * @param value The value of 'key_defs'.
      * @return This builder.
      */
    public eosio.nft.ft.AddkeysAActionParams.Builder setKeyDefs(java.util.List<eosio.nft.ft.KeyDefAction> value) {
      validate(fields()[1], value);
      this.key_defs = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'key_defs' field has been set.
      * @return True if the 'key_defs' field has been set, false otherwise.
      */
    public boolean hasKeyDefs() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'key_defs' field.
      * @return This builder.
      */
    public eosio.nft.ft.AddkeysAActionParams.Builder clearKeyDefs() {
      key_defs = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'memo' field.
      * @return The value.
      */
    public java.lang.CharSequence getMemo() {
      return memo;
    }


    /**
      * Sets the value of the 'memo' field.
      * @param value The value of 'memo'.
      * @return This builder.
      */
    public eosio.nft.ft.AddkeysAActionParams.Builder setMemo(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.memo = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'memo' field has been set.
      * @return True if the 'memo' field has been set, false otherwise.
      */
    public boolean hasMemo() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'memo' field.
      * @return This builder.
      */
    public eosio.nft.ft.AddkeysAActionParams.Builder clearMemo() {
      memo = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AddkeysAActionParams build() {
      try {
        AddkeysAActionParams record = new AddkeysAActionParams();
        record.factory_id = fieldSetFlags()[0] ? this.factory_id : (java.lang.Long) defaultValue(fields()[0]);
        record.key_defs = fieldSetFlags()[1] ? this.key_defs : (java.util.List<eosio.nft.ft.KeyDefAction>) defaultValue(fields()[1]);
        record.memo = fieldSetFlags()[2] ? this.memo : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AddkeysAActionParams>
    WRITER$ = (org.apache.avro.io.DatumWriter<AddkeysAActionParams>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AddkeysAActionParams>
    READER$ = (org.apache.avro.io.DatumReader<AddkeysAActionParams>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










