/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eosio.nft.ft;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class KeyDefAction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8647743771006839022L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KeyDefAction\",\"namespace\":\"eosio.nft.ft\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"eos.type\":\"string\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"eos.type\":\"string\"}},{\"name\":\"edit_rights\",\"type\":{\"type\":\"int\",\"eos.type\":\"uint8\"}},{\"name\":\"editors\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"eos.type\":\"name\"}}},{\"name\":\"default_value\",\"type\":[\"null\",{\"type\":\"int\",\"eos.type\":[\"int8\",\"int16\"]},{\"type\":\"long\",\"eos.type\":\"int64\"},{\"type\":\"float\",\"eos.type\":\"float32\"},{\"type\":\"double\",\"eos.type\":\"float64\"},{\"type\":\"string\",\"eos.type\":\"string\"},{\"type\":\"bytes\",\"eos.type\":\"bytes\"},{\"type\":\"array\",\"items\":[{\"type\":\"int\",\"eos.type\":[\"int16\",\"int32\"]}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<KeyDefAction> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<KeyDefAction> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<KeyDefAction> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<KeyDefAction> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<KeyDefAction> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this KeyDefAction to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a KeyDefAction from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a KeyDefAction instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static KeyDefAction fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.CharSequence type;
  private int edit_rights;
  private java.util.List<java.lang.CharSequence> editors;
  private java.lang.Object default_value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KeyDefAction() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param type The new value for type
   * @param edit_rights The new value for edit_rights
   * @param editors The new value for editors
   * @param default_value The new value for default_value
   */
  public KeyDefAction(java.lang.CharSequence name, java.lang.CharSequence type, java.lang.Integer edit_rights, java.util.List<java.lang.CharSequence> editors, java.lang.Object default_value) {
    this.name = name;
    this.type = type;
    this.edit_rights = edit_rights;
    this.editors = editors;
    this.default_value = default_value;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return type;
    case 2: return edit_rights;
    case 3: return editors;
    case 4: return default_value;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: edit_rights = (java.lang.Integer)value$; break;
    case 3: editors = (java.util.List<java.lang.CharSequence>)value$; break;
    case 4: default_value = value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'edit_rights' field.
   * @return The value of the 'edit_rights' field.
   */
  public int getEditRights() {
    return edit_rights;
  }


  /**
   * Sets the value of the 'edit_rights' field.
   * @param value the value to set.
   */
  public void setEditRights(int value) {
    this.edit_rights = value;
  }

  /**
   * Gets the value of the 'editors' field.
   * @return The value of the 'editors' field.
   */
  public java.util.List<java.lang.CharSequence> getEditors() {
    return editors;
  }


  /**
   * Sets the value of the 'editors' field.
   * @param value the value to set.
   */
  public void setEditors(java.util.List<java.lang.CharSequence> value) {
    this.editors = value;
  }

  /**
   * Gets the value of the 'default_value' field.
   * @return The value of the 'default_value' field.
   */
  public java.lang.Object getDefaultValue() {
    return default_value;
  }


  /**
   * Sets the value of the 'default_value' field.
   * @param value the value to set.
   */
  public void setDefaultValue(java.lang.Object value) {
    this.default_value = value;
  }

  /**
   * Creates a new KeyDefAction RecordBuilder.
   * @return A new KeyDefAction RecordBuilder
   */
  public static eosio.nft.ft.KeyDefAction.Builder newBuilder() {
    return new eosio.nft.ft.KeyDefAction.Builder();
  }

  /**
   * Creates a new KeyDefAction RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new KeyDefAction RecordBuilder
   */
  public static eosio.nft.ft.KeyDefAction.Builder newBuilder(eosio.nft.ft.KeyDefAction.Builder other) {
    if (other == null) {
      return new eosio.nft.ft.KeyDefAction.Builder();
    } else {
      return new eosio.nft.ft.KeyDefAction.Builder(other);
    }
  }

  /**
   * Creates a new KeyDefAction RecordBuilder by copying an existing KeyDefAction instance.
   * @param other The existing instance to copy.
   * @return A new KeyDefAction RecordBuilder
   */
  public static eosio.nft.ft.KeyDefAction.Builder newBuilder(eosio.nft.ft.KeyDefAction other) {
    if (other == null) {
      return new eosio.nft.ft.KeyDefAction.Builder();
    } else {
      return new eosio.nft.ft.KeyDefAction.Builder(other);
    }
  }

  /**
   * RecordBuilder for KeyDefAction instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KeyDefAction>
    implements org.apache.avro.data.RecordBuilder<KeyDefAction> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence type;
    private int edit_rights;
    private java.util.List<java.lang.CharSequence> editors;
    private java.lang.Object default_value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eosio.nft.ft.KeyDefAction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.edit_rights)) {
        this.edit_rights = data().deepCopy(fields()[2].schema(), other.edit_rights);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.editors)) {
        this.editors = data().deepCopy(fields()[3].schema(), other.editors);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.default_value)) {
        this.default_value = data().deepCopy(fields()[4].schema(), other.default_value);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing KeyDefAction instance
     * @param other The existing instance to copy.
     */
    private Builder(eosio.nft.ft.KeyDefAction other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.edit_rights)) {
        this.edit_rights = data().deepCopy(fields()[2].schema(), other.edit_rights);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.editors)) {
        this.editors = data().deepCopy(fields()[3].schema(), other.editors);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.default_value)) {
        this.default_value = data().deepCopy(fields()[4].schema(), other.default_value);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'edit_rights' field.
      * @return The value.
      */
    public int getEditRights() {
      return edit_rights;
    }


    /**
      * Sets the value of the 'edit_rights' field.
      * @param value The value of 'edit_rights'.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder setEditRights(int value) {
      validate(fields()[2], value);
      this.edit_rights = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'edit_rights' field has been set.
      * @return True if the 'edit_rights' field has been set, false otherwise.
      */
    public boolean hasEditRights() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'edit_rights' field.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder clearEditRights() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'editors' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getEditors() {
      return editors;
    }


    /**
      * Sets the value of the 'editors' field.
      * @param value The value of 'editors'.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder setEditors(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.editors = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'editors' field has been set.
      * @return True if the 'editors' field has been set, false otherwise.
      */
    public boolean hasEditors() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'editors' field.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder clearEditors() {
      editors = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'default_value' field.
      * @return The value.
      */
    public java.lang.Object getDefaultValue() {
      return default_value;
    }


    /**
      * Sets the value of the 'default_value' field.
      * @param value The value of 'default_value'.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder setDefaultValue(java.lang.Object value) {
      validate(fields()[4], value);
      this.default_value = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'default_value' field has been set.
      * @return True if the 'default_value' field has been set, false otherwise.
      */
    public boolean hasDefaultValue() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'default_value' field.
      * @return This builder.
      */
    public eosio.nft.ft.KeyDefAction.Builder clearDefaultValue() {
      default_value = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public KeyDefAction build() {
      try {
        KeyDefAction record = new KeyDefAction();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.edit_rights = fieldSetFlags()[2] ? this.edit_rights : (java.lang.Integer) defaultValue(fields()[2]);
        record.editors = fieldSetFlags()[3] ? this.editors : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        record.default_value = fieldSetFlags()[4] ? this.default_value :  defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<KeyDefAction>
    WRITER$ = (org.apache.avro.io.DatumWriter<KeyDefAction>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<KeyDefAction>
    READER$ = (org.apache.avro.io.DatumReader<KeyDefAction>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










